name: Build Docker Image

on:
  workflow_dispatch:
    inputs:
      context:
        required: true
        type: choice
        description: build context
        options:
        - backend
        - frontend

jobs:
  build_and_push_to_registry:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ${{ github.event.inputs.context }}/Dockerfile
          push: true
          tags: ${{ github.repository }}-${{ github.event.inputs.context }}:latest
          cache-from: type=registry,ref=${{ github.repository }}-${{ github.event.inputs.context }}:buildcache
          cache-to: type=registry,ref=${{ github.repository }}-${{ github.event.inputs.context }}:buildcache,mode=max
